"""index

Revision ID: 073ad9918f02
Revises: 67ff5a286caf
Create Date: 2024-11-21 20:13:08.743608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073ad9918f02'
down_revision: Union[str, None] = '67ff5a286caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chats_lang'), 'chats', ['lang'], unique=False)
    op.create_index(op.f('ix_words_translation_en'), 'words', ['translation_en'], unique=False)
    op.create_index(op.f('ix_words_translation_ru'), 'words', ['translation_ru'], unique=False)
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_index(op.f('ix_words_translation_ru'), table_name='words')
    op.drop_index(op.f('ix_words_translation_en'), table_name='words')
    op.drop_index(op.f('ix_chats_lang'), table_name='chats')
    # ### end Alembic commands ###
