"""ChatActivityStatistic

Revision ID: c80a415d2903
Revises: 073ad9918f02
Create Date: 2024-12-03 11:53:29.643906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80a415d2903'
down_revision: Union[str, None] = '073ad9918f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats_event_statistics',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'date')
    )
    op.create_index(op.f('ix_chats_event_statistics_date'), 'chats_event_statistics', ['date'], unique=False)
    op.create_index(op.f('ix_chats_event_statistics_event_count'), 'chats_event_statistics', ['event_count'], unique=False)
    op.create_index(op.f('ix_chats_statistics_status'), 'chats_statistics', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_statistics_status'), table_name='chats_statistics')
    op.drop_index(op.f('ix_chats_event_statistics_event_count'), table_name='chats_event_statistics')
    op.drop_index(op.f('ix_chats_event_statistics_date'), table_name='chats_event_statistics')
    op.drop_table('chats_event_statistics')
    # ### end Alembic commands ###
