"""Chats

Revision ID: cb162d85d4c3
Revises: 999aef9ef447
Create Date: 2024-10-29 17:03:17.037329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb162d85d4c3'
down_revision: Union[str, None] = '999aef9ef447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('chats_current_words',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.word_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'word_id')
    )
    op.create_table('chats_info',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('chats_statistics',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('wrong', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.word_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'word_id')
    )
    op.drop_table('users_statistics')
    op.drop_table('users_current_words')
    op.add_column('users', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language_code', sa.String(), nullable=True))
    op.drop_column('users', 'frequency')
    op.drop_column('users', 'lang')
    op.drop_column('users', 'end_time')
    op.drop_column('users', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('end_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('lang', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'language_code')
    op.drop_column('users', 'username')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'chat_id')
    op.create_table('users_current_words',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('word_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='users_current_words_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.word_id'], name='users_current_words_word_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'word_id', name='users_current_words_pkey')
    )
    op.create_table('users_statistics',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wrong', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='users_statistics_user_id_fkey'),
    sa.ForeignKeyConstraint(['word_id'], ['words.word_id'], name='users_statistics_word_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'word_id', name='users_statistics_pkey')
    )
    op.drop_table('chats_statistics')
    op.drop_table('chats_info')
    op.drop_table('chats_current_words')
    op.drop_table('chats')
    # ### end Alembic commands ###
