"""ChatActivityStatistic foreing key

Revision ID: a37e911067aa
Revises: c80a415d2903
Create Date: 2024-12-03 16:36:15.953932

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a37e911067aa"
down_revision: Union[str, None] = "c80a415d2903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "chats_event_statistics_chat_id_fkey",
        "chats_event_statistics",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "chats_event_statistics_chat_id_fkey",
        "chats_event_statistics",
        "chats",
        ["chat_id"],
        ["chat_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
