"""First migration

Revision ID: 999aef9ef447
Revises:
Create Date: 2024-10-24 20:36:20.946450

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "999aef9ef447"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.Integer(), nullable=True),
        sa.Column("end_time", sa.Integer(), nullable=True),
        sa.Column("lang", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "words",
        sa.Column("word_id", sa.BigInteger(), nullable=False),
        sa.Column("word", sa.String(), nullable=True),
        sa.Column("translation_ru", sa.String(), nullable=True),
        sa.Column("translation_en", sa.String(), nullable=True),
        sa.Column("example", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("word_id"),
    )
    op.create_table(
        "users_current_words",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("word_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["word_id"], ["words.word_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "word_id"),
    )
    op.create_table(
        "users_statistics",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Integer(), nullable=True),
        sa.Column("wrong", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("status_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(["word_id"], ["words.word_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "word_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_statistics")
    op.drop_table("users_current_words")
    op.drop_table("words")
    op.drop_table("users")
    # ### end Alembic commands ###
