"""chat start date

Revision ID: 67ff5a286caf
Revises: b03d08a17b74
Create Date: 2024-11-12 13:15:54.803214

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67ff5a286caf"
down_revision: Union[str, None] = "b03d08a17b74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats_info",
        sa.Column(
            "start_date",
            sa.DateTime(timezone=True),
            server_default="0001-01-01",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats_info", "start_date")
    # ### end Alembic commands ###
