"""examples ru en

Revision ID: d77d53cd0f5c
Revises: a37e911067aa
Create Date: 2024-12-06 20:27:50.972082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77d53cd0f5c'
down_revision: Union[str, None] = 'a37e911067aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('example_ru', sa.String(), nullable=True))
    op.add_column('words', sa.Column('example_en', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'example_en')
    op.drop_column('words', 'example_ru')
    # ### end Alembic commands ###
