"""count current words

Revision ID: b553559c2cfb
Revises: cb162d85d4c3
Create Date: 2024-10-30 13:18:45.159557

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b553559c2cfb"
down_revision: Union[str, None] = "cb162d85d4c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats",
        sa.Column("count_current", sa.Integer(), nullable=True, server_default="10"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "count_current")
    # ### end Alembic commands ###
