"""blocked_bot

Revision ID: b03d08a17b74
Revises: b553559c2cfb
Create Date: 2024-11-05 13:28:44.973313

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b03d08a17b74"
down_revision: Union[str, None] = "b553559c2cfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats",
        sa.Column("blocked_bot", sa.Boolean(), server_default="False", nullable=True),
    )
    op.drop_constraint("chats_info_chat_id_fkey", "chats_info", type_="foreignkey")
    op.create_foreign_key(None, "chats_info", "chats", ["chat_id"], ["chat_id"], ondelete="CASCADE")
    op.drop_constraint("chats_statistics_chat_id_fkey", "chats_statistics", type_="foreignkey")
    op.create_foreign_key(None, "chats_statistics", "chats", ["chat_id"], ["chat_id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "blocked_bot")
    op.drop_constraint(None, "chats_statistics", type_="foreignkey")
    op.create_foreign_key(
        "chats_statistics_chat_id_fkey",
        "chats_statistics",
        "chats",
        ["chat_id"],
        ["chat_id"],
    )
    op.drop_constraint(None, "chats_info", type_="foreignkey")
    op.create_foreign_key("chats_info_chat_id_fkey", "chats_info", "chats", ["chat_id"], ["chat_id"])
    # ### end Alembic commands ###
