"""type of word

Revision ID: 3778fe160734
Revises: d77d53cd0f5c
Create Date: 2025-01-06 10:23:59.521159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3778fe160734'
down_revision: Union[str, None] = 'd77d53cd0f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('type', sa.String(), nullable=True))
    op.create_index(op.f('ix_words_type'), 'words', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_type'), table_name='words')
    op.drop_column('words', 'type')
    # ### end Alembic commands ###
